
---
test_name: Textresource create/edit/delete

includes:
  - !include includes.yaml

stages:
  - name: Verify textresource create API
    request:
      url: "{SERVER_ROOT:s}/parallel/textresources/multi_locales_add/"
      method: POST
      json:
        product: "vTaaS"
        key: "text-key-01"
        en_US: "key-01-en-US"
        zh_CN: "key-01-zh-CN"
    response:
      strict:
        - json:off
      status_code: 200

---
test_name: textresource edit

includes:
  - !include includes.yaml

stages:
  - name: Verify textresource edit API
    request:
      url: "{SERVER_ROOT:s}/parallel/textresources/multi_locales_update/"
      method: POST
      json:
        product: "vTaaS"
        key: "text-key-01"
        en_US: "key-02-en-US"
        zh_CN: "key-02-zh-CN"
    response:
      strict:
        - json:off
      status_code: 200

---
test_name: textresource search

includes:
  - !include includes.yaml

stages:
  - name: Verify textresource search API
    request:
      url: "{SERVER_ROOT:s}/parallel/textresources/search/"
      method: POST
      json:
        product: "vTaaS"
        locale: ["zh_CN", "en_US"]
        resultStyle: "locale-row"
    response:
      strict:
        - json:off
      status_code: 200

---
test_name: textresource delete_by_product

includes:
  - !include includes.yaml

stages:
  - name: Verify textresource delete_by_product API
    request:
      url: "{SERVER_ROOT:s}/parallel/textresources/delete_by_product_keys/"
      method: POST
      json:
        product: "vTaaS"
        keys: ["text-key-01"]
    response:
      strict:
        - json:off
      status_code: 200

---
test_name: textresource import_resource_text

includes:
  - !include includes.yaml

stages:
  - name: Verify textresource import_resource_text API
    request:
      url: "{SERVER_ROOT:s}/parallel/textresources/import_resource_text/"
      method: POST
      json:
        product: "vTaaS"
        format: "properties"
        resourceFiles: [{"path": "tr/tr.properties", "locale": "zh_CN", "keyPrefix": "tr", "content": "login=LogIn↵login.desc=the button to login"}]
    response:
      strict:
        - json:off
      status_code: 200
