
---
test_name: Parallel test stop

includes:
  - !include includes.yaml

stages:
  - name: Verify parallel stop API
    request:
      url: "{SERVER_ROOT:s}/parallel/operate/"
      method: POST
      json:
        operation: "stop"
        tests: "['7cd9f75a-b218-4c79-be31-0b018cfe6d38']"
    response:
      strict:
        - json:off
      status_code: 200
      json:
        message: 'success'


---
test_name: Parallel test start

includes:
  - !include includes.yaml

stages:
  - name: Verify parallel start API
    request:
      url: "{SERVER_ROOT:s}/parallel/operate/"
      method: POST
      json:
        operation: "start"
        pool: ""
        tests: "['7cd9f75a-b218-4c79-be31-0b018cfe6d38']"
    response:
      strict:
        - json:off
      status_code: 200
      json:
        message: 'success'
    delay_after: 10

---
test_name: Parallel test stop

includes:
  - !include includes.yaml

stages:
  - name: Verify parallel stop API
    request:
      url: "{SERVER_ROOT:s}/parallel/operate/"
      method: POST
      json:
        operation: "stop"
        tests: "['7cd9f75a-b218-4c79-be31-0b018cfe6d38']"
    response:
      strict:
        - json:off
      status_code: 200
      json:
        message: 'success'

---
test_name: Automation test stop

includes:
  - !include includes.yaml

stages:
  - name: Verify parallel stop API
    request:
      url: "{SERVER_ROOT:s}/parallel/operate/"
      method: POST
      json:
        operation: "stop"
        tests: "['89b26523-7bab-48f0-8ea5-1e6591d7ae07']"
    response:
      strict:
        - json:off
      status_code: 200
      json:
        message: 'success'


---
test_name: Automation test start

includes:
  - !include includes.yaml

stages:
  - name: Verify parallel start API
    request:
      url: "{SERVER_ROOT:s}/parallel/operate/"
      method: POST
      json:
        operation: "start"
        pool: ""
        tests: "['89b26523-7bab-48f0-8ea5-1e6591d7ae07']"
    response:
      strict:
        - json:off
      status_code: 200
      json:
        message: 'success'
    delay_after: 10

---
test_name: Automation test stop

includes:
  - !include includes.yaml

stages:
  - name: Verify parallel stop API
    request:
      url: "{SERVER_ROOT:s}/parallel/operate/"
      method: POST
      json:
        operation: "stop"
        tests: "['89b26523-7bab-48f0-8ea5-1e6591d7ae07']"
    response:
      strict:
        - json:off
      status_code: 200
      json:
        message: 'success'


---
test_name: Accessibility test stop

includes:
  - !include includes.yaml

stages:
  - name: Verify parallel stop API
    request:
      url: "{SERVER_ROOT:s}/parallel/operate/"
      method: POST
      json:
        operation: "stop"
        tests: "['e1e59c6a-9dd3-4bd3-8f6d-e9e4308815c5']"
    response:
      strict:
        - json:off
      status_code: 200
      json:
        message: 'success'


---
test_name: Accessibility test start

includes:
  - !include includes.yaml

stages:
  - name: Verify parallel start API
    request:
      url: "{SERVER_ROOT:s}/parallel/operate/"
      method: POST
      json:
        operation: "start"
        pool: ""
        tests: "['e1e59c6a-9dd3-4bd3-8f6d-e9e4308815c5']"
    response:
      strict:
        - json:off
      status_code: 200
      json:
        message: 'success'
    delay_after: 10

---
test_name: Accessibility test stop

includes:
  - !include includes.yaml

stages:
  - name: Verify parallel stop API
    request:
      url: "{SERVER_ROOT:s}/parallel/operate/"
      method: POST
      json:
        operation: "stop"
        tests: "['e1e59c6a-9dd3-4bd3-8f6d-e9e4308815c5']"
    response:
      strict:
        - json:off
      status_code: 200
      json:
        message: 'success'

---
test_name: Post executeuievents/ids

includes:
  - !include includes.yaml

stages:
  - name: Verify executeuievents/ids API
    request:
      url: "{SERVER_ROOT:s}/parallel/executeuievents/ids/"
      method: POST
      json:
        scriptIds: ['5863']
    response:
      strict:
        - json:off
      status_code: 200
